### PR TITLE
Readd depreceated

### PR DESCRIPTION
**Pull request by DizzyBHigh**
Added LastSeason and UpcomingSeason

### CODE REVIEW

**Comment by oakensoul** [comment]
Most of these look good, could you update the Tests to go with them too? There should be decent guidelines in the Testing.md file.

Also, i’m going to start working on the V2 updates to use the new http://api.nfldata.apiphany.com/nfl/v2/ version. I’ll get that going asap. Ideally, for the future, if you could break these updates into smaller pull requests with the tests included it will be easier for me to merge them in.

Thanks!

**Comment by oakensoul** [comment]
Also, my apologies that took so long. I didn’t realize my GitHub emails were going to an older email address and I had forgot to hook this repository up to HipChat.

**Comment by DizzyBHigh** [comment]
Hey there, This is my first time at using github/symfony2 properly, I'll have a look at how to write the tests. I'll also try to add the changes as separate pulls as well.

**Comment by oakensoul** [comment]
Great thanks! If you use the tests and the Vagrant environment, you can test your changes without needing Symphony2. If you have any questions on how to do that, please let me know. I'll let you know when I start the V2 version since the V1 is deprecating in 9 days.

**Comment by DizzyBHigh** [comment]
Hey there, I do have vagrant installed along with Oracle VM Virtual box though i have never actually got as far as having a vm running.
So if you could outline the steps needed to get the vagrant environment up and running would be really useful, Then i can start looking into making tests with phpunit, another thing i have no experience in as yet! though reading through your .mdon the testing is making things a little clearer.

**Comment by oakensoul** [comment]
You’ll need to install VirtualBox if you haven’t done that. https://www.virtualbox.org/wiki/Downloads

Then, you should run the following command (only once)
vagrant plugin install vagrant-vbguest

After that, just go to the project root folder, and type “vagrant up”

To SSH into the box, you type “vagrant ssh”
To stop the box, vagrant halt
To destroy the box, vagrant destroy
To start it back up, vagrant up

They have some decent documentation for the specifics: http://docs.vagrantup.com/v2/getting-started/index.html

**Comment by DizzyBHigh** [comment]
I've closed this pull request, I'm going to wait until the v2 changes have been put in place, and then i'll readd them (if needed) make the tests and put in new pull requests.

**Pull request closed without merging**
